source ./.env

docker run --rm=true \
  -e POSTGRES_USER="$PETCLINIC_DATABASE_USERNAME" \
  -e POSTGRES_PASSWORD="$PETCLINIC_DATABASE_PASSWORD" \
  -e POSTGRES_DB="$PETCLINIC_DATABASE_SCHEMA" \
  -p "$PETCLINIC_DATABASE_PORT":5432 \
  postgres:14

